export const figmaInstanceNameToUI5ControlMap = {
	".base/Input Label": "sap.m.Label",
	".base/Input Field": "sap.m.Input",
	Button: "sap.m.Button",
	"Radio Button": "sap.m.RadioButton",
	Select: "sap.m.Select",
	"Date Picker": "sap.m.DatePicker",
	Table: "sap.m.Table",
	"List Item": "sap.m.StandardListItem",
	"Page Title": "sap.m.Title",
	Label: "sap.m.Label",
	"Text Area": "sap.m.TextArea",
	"Search Field": "sap.m.SearchField",
	Card: "sap.f.Card",
	Panel: "sap.m.Panel",
	Dialog: "sap.m.Dialog",
	"Message Strip": "sap.m.MessageStrip",
	"Progress Indicator": "sap.m.ProgressIndicator",
	Slider: "sap.m.Slider",
	Switch: "sap.m.Switch",
	"Segmented Button": "sap.m.SegmentedButton",
	Toolbar: "sap.m.Toolbar",
	"Object Header": "sap.m.ObjectHeader",
	"Simple Form": "sap.ui.layout.form.SimpleForm",
	"Form Container": "sap.ui.layout.form.FormContainer",
	"Form Element": "sap.ui.layout.form.FormElement",
	"Icon TabBar": "sap.m.IconTabBar",
	IconTabFilter: "sap.m.IconTabFilter",
	Link: "sap.m.Link",
	Breadcrumbs: "sap.m.Breadcrumbs",
	"Busy Indicator": "sap.m.BusyIndicator",
	"Rating Indicator": "sap.m.RatingIndicator",
	"File Uploader": "sap.ui.unified.FileUploader",
	"Split Container": "sap.m.SplitContainer",
	Popover: "sap.m.Popover",
	"Responsive Popover": "sap.m.ResponsivePopover",
	Carousel: "sap.m.Carousel",
	"Nav Container": "sap.m.NavContainer",
	"Feed Input": "sap.m.FeedInput",
	"Feed List Item": "sap.m.FeedListItem",
	"Upload Collection": "sap.m.UploadCollection",
	"View Settings Dialog": "sap.m.ViewSettingsDialog",
	"Horizontal Layout": "sap.m.HBox",
	"Vertical Layout": "sap.m.VBox",
	"Grid Layout": "sap.ui.layout.Grid",
	FlexBox: "sap.m.FlexBox",
} as const;
